language: go

sudo: false

go:
  - 1.11
  - 1.12
  - 1.13

before_install:
    - curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` > $GOPATH/bin/docker-machine && chmod +x $GOPATH/bin/docker-machine

install:
    - go install

script:
    docker-machine create -d scaleway -h | grep "scaleway"
